# See the specific doc of your producer to understand values
fix-engine:
  party-id-source: 'C'
  party-role: 11
  sender-comp-id: MYIDENTITYPRD
  sender-location-id: LOCATION NAME
  time-in-force: '0'
  symbol: '[N/A]'
  security-id-source: "1"
  target-comp-id: PRODUCERIDENTITYPRD
  conf: Maukaim/configuration/client/fixconf-prd.cfg # ADD module name if multi-module project
